name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: macOS-11

    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app

    - name: Build and test macOS
      run: xcodebuild clean build test -project Feed.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
    
    - name: Build and test iOS
      run: xcodebuild clean build test -project Feed.xcodeproj -scheme "CI_iOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator, id=25A9E533-83F9-418B-BA37-3F3BDB24CE56, OS=15.2, name=iPhone 11 Pro Max" ONLY_ACTIVE_ARCH=YES
